sudo: required
language: generic
services:
  - docker

before_install:
  - echo "before install"

install:
  - echo "install nothing"

script:
  - echo "no tests"

after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws ecr get-login-password --region us-east-1
  - docker build -t docker-node-api02 .
  - bash docker_push.sh
  - bash ecs_deploy.sh
  
env:
  global:
  - DOCKER_REPO=docker-node-api02
  - EB_REGION="us-east-1"
  - LIVE_SERVICE=santoro-fargate-service02
  - LIVE_CLUSTER_NAME=santoro-ecs-cluster02
  - AWS_PAGER=""
  - secure: aIWoPQp9yDnE+HefHIf39sMSXdtkFfEO29k00tzgSg7kmfrDHCJ5DhNC2yS6zA3E7Y13ZOYoUiLYux8larxu8P2PMpTDpBDcBU/s+IBrB630AOQhD6d10KjcrG3IkMa/mw9M4r9B0u4nFxKqHGUW62KyxanTwOOKVKSprDVJ7R2gF3S40ZE/gujk2P6h7AhiKJxVog0d50/8xwq9Av0xJ9COIsW9KD7xQR/pg6AluT67jKv8l2ApXatkGI7OebsS5VrbtTSTdUR4cCFmZM2T5J0PdnudGQVAMqNxtBi+ToRkYoMCyJ+8vo0vYo6c8OgyRqada8DnjC7vJ4UPQPJXSPG9oLINZd2JL7SJrAQzO6/oC5aDYfCgGvApGAKjSES+xATQukDnwFFzdCAq9JnXNGo3yVlmDLvJZE4ma1ChDDqM+3Z/2JkMqAyBDSBbX60TJOXEnG1P9IhXLPdm4F3I5F366V9yUxBAkf+rrSy5b1SJBWk0cb25d9x057Py6osc6o8IH4YLEPvdKHNq0ccT+ZO1ioHLR5mk+9HFFZuv/k1w5NYQIKYpepNZy1Cni7tCMK7mGESzylhcaCyoYOzyEmsGzEH5qSlTUPRkqnySyY/XW//DUNJlznDGHiI5CUr9+vTKqvxaPtx/syFsB8ybCNqWcEJYl158qsgBr7MN+94=
  - secure: b5jTtXtOR9800gLsngUNlI6+1mFjNstoxumFhWPQ4Kd3k4PLy0JpcMt81VOm6lqrBYYm7UO3DV/ll3hS8ItSDoywqp3ITg5B+6dKgMsXitJbHm5kCuWGMJBIfcW4J8rki7g4Aq2R3RRJ3/dEWDzndxW9HyiHnFcGYftoJVaqMBZl4zIBQmi+DR4JLIHDL99zuJIK3B5gLQ7lV9YFVMIz4uCle2789e2ijwU4M+uordYZJyT2aj5KuExv54FcBiFlDN54DxVCB5wootyttdiBt++LTfNritS0SHbauAsIJ91bmrCpZ9sxWDQwCmeHQhgwpRG989b95Td1NVGlC0Va5oitmb1B/DZEXaxqXKRL5wt02Ehu+R0EaonZTJ5Cyp9Eh7Uh7aHknE8up6pK4PyOGlThOHDOu6NSNqEiNXD5OeHjJ/tLMAHeUXLS+EIq8GzTvtK2BASlZRB6k0u6nzCLpl0Azv2n1CgCjVV9UVcHR9Zrr1YXinEWF4d+OeP1ZUgAUXzls+vGlMijleeCqq4+iT7eNKnP83yN/2xtTcdzKotLSovzv1CcUp5RBf4lJpUasWpwSbsP8BHiorpRx1YshCNjwZAChpEEOsUMt2onGHA9PdE4djmNKEqBodcoGLx/hASvbf3HqUBBGIpIAA2X8QkjENI3q4g+N5ZdtxgnBR0=
  - secure: MQio1zeb5w/u12fkbA1vdtt9IBS8udGKIaU4hLfgsBIiddChgTUwsheA/v6SmziDU3XAJGV2UEdChUi0sh/EqgnHCh2nBZzNRJQUxBMs2PNaYQq4xxwi+WR+vTX3bWQQ3ySywOg5lbT3R147IWox6ca6aEZoTvFRjZ3bI/PEXYL6ZtrXff2lrNrR6ZDYdf+vEN55gPUUIyun2cXsiPEAF2wm0LMkIn73Xh+LO7ZXmd/3/6KuWKoPNU2fd2tCelb6jlBAolk1wWaZpeuleIgzitqen9MC71Wuq/I1QlRbw64cJzCzDOYzaReOElQovfwphaNeKTNs24S/h4ZdlE9Wl/xraAlBPDMqhwTfXfgHvwa4SwDU7tGjKMpSiqg6TzyKvZPaW8Lpuq+sB7ay0TFCsjX3CPmNOegdysmu+ZmwwDL/H+SeLAMmq6n0eGGJOc9j5RNJ8I2UI7NosbB1XgVu1/8SLdwSU0kpovjhfaepFBt0Rkg6wdes69DiRDWEE8a0JPnPS3jCDoSJ0sU/+5Ka+uqCPU4uu9OHVDPJazrDm17MPQvWDvbCEhv2xSZde0xxvfKEU7q0Hnv1Jo0YdpKSuSR50c2BBeZnWBKaNGp2xIn5FCg8dj0HPpVST4funcAxeK0NsPMeoa/Lby7a59Tmp/E53SRug/lWDo5rncC/zkk=
